### ISSUE TITLE
Question: Blackfire

### ISSUE THREAD

**Issue by Fichtme** [Baldinof/roadrunner-bundle#64]
Hi!

We just recently started using blackfire.

The documentation says that the bundle supports blackfire, but how do i use it in an api application?

- I cannot use the blackfire cli.
- I installed the blackfire sdk
- tried this, but it looks like register_shutdown_function is never called.

```php
// let's create a client
$blackfire = new \Blackfire\Client();
// then start the probe
$probe = $blackfire->createProbe();

// When runtime shuts down, let's finish the profiling session
register_shutdown_function(function () use ($blackfire, $probe) {
    // See the PHP SDK documentation for using the $profile object
    $profile = $blackfire->endProbe($probe);
    dd('stopped');
});
```

Any help would be much appreciated!

**Comment by Baldinof** [comment]
Hi!

Thank you for using this bundle :)

The integration starts and stop the probe for http requests, so that you can use `blackfire curl <your url>` or the blackfire browser extension.

The goal of the integration is to work the same as it does when using php fpm, so you should be able to profile  with `blackfire curl`.

**Comment by Fichtme** [comment]
I'll look into this. Thnx for your time!

**Comment by Baldinof** [comment]
👍  Do not hesitate to repost here if you have any problem :)
