### ISSUE TITLE
Whats a point of bundle?

### ISSUE THREAD

**Issue by tony-sol** [Baldinof/roadrunner-bundle#73]
Sorry for this so abstract question, but what purpose of bundle - maybe it's a lack of documentation? (index.php or worker.php examples could make it more clear)
I'm trying to get RR into symfony 6 and found this, but not really sure what problem it solves.
It's not quite merge with RR official doc for 2.8 version.

I'll be really glad for guide me to any examples of usage this bundle.

(Sorry for issue, it should be a discussion, but this is only one i can create)

**Comment by Baldinof** [comment]
Hi!

I don't know if you closed this because you found your answer, but I can give you an explaination.

The purpose of this bundle is to have a good integration of RR with Symfony, and it's ecosystem:

- Sessions and StreamedResponse works out of the box (it's now fixed in Symfony core 5.4 for sessions and StreamedResponse will be in 6.1)
- Integration with the ecosystem: manage Doctrine connections, works with Blackfire, Sentry, ...
- Simplification of some challenges brought by the long running process approach (ie, `RebootStrategy` you may want to fully reboot the kernel in some cases)
- Integration with RR: metrics, gRPC works out of the box (some other integration could be added, like messenger, cache, temporal, ...)
- better performance: it include a direct bridge to RR to convert RR payloads to HttpFoundation Request/Response. In most implementation, RR payloads are converted to PSR7, and then to HttpFoundation

**Comment by tony-sol** [comment]
Yeah, i found answer and immediately felt ashamed for such a stupid question
Thanks for additional explanation!

**Comment by Baldinof** [comment]
No problem, thanks for you interest in this package :)
